
spring:
  datasource:
    url: jdbc:sqlite:${db.path}
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  thymeleaf:
    cache: false
  #设置当前的参数版本
  profiles:
    active: window
  #设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
#    type: com.mchange.v2.c3p0.ComboPooledDataSource
mybatis-plus:
  mapper-locations: classpath:com/media/video_meeting/dao/mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.media.video_meeting.entity

#日志设置
logging:
  config: classpath:log4j2.xml
page:
  size: 10

#golang服务器注册地址
golang:
  serverpath: ws://47.107.235.165:8000/
server:
  port: 8080
---
server:
  os: window
db:
  path: C:/Users/ken/Desktop/admin_hy/Meeting.db
spring:
  profiles: window
upload:
  path: C:/Users/ken/Desktop/admin_hy/imgs

---
server:
  os: linux
db:
  path: /usr/local/software/Meeting.db
spring:
  profiles: linux
upload:
  path: