package com.media.video_meeting.entity;

import java.io.Serializable;

public class Branch implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.priority
     *
     * @mbggenerated
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.proxy
     *
     * @mbggenerated
     */
    private String proxy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.clients
     *
     * @mbggenerated
     */
    private String clients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table branch
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.id
     *
     * @return the value of branch.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.id
     *
     * @param id the value for branch.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.username
     *
     * @return the value of branch.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.username
     *
     * @param username the value for branch.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.password
     *
     * @return the value of branch.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.password
     *
     * @param password the value for branch.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.nickname
     *
     * @return the value of branch.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.nickname
     *
     * @param nickname the value for branch.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.priority
     *
     * @return the value of branch.priority
     *
     * @mbggenerated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.priority
     *
     * @param priority the value for branch.priority
     *
     * @mbggenerated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.proxy
     *
     * @return the value of branch.proxy
     *
     * @mbggenerated
     */
    public String getProxy() {
        return proxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.proxy
     *
     * @param proxy the value for branch.proxy
     *
     * @mbggenerated
     */
    public void setProxy(String proxy) {
        this.proxy = proxy == null ? null : proxy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.clients
     *
     * @return the value of branch.clients
     *
     * @mbggenerated
     */
    public String getClients() {
        return clients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.clients
     *
     * @param clients the value for branch.clients
     *
     * @mbggenerated
     */
    public void setClients(String clients) {
        this.clients = clients == null ? null : clients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Branch other = (Branch) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getPriority() == null ? other.getPriority() == null : this.getPriority().equals(other.getPriority()))
            && (this.getProxy() == null ? other.getProxy() == null : this.getProxy().equals(other.getProxy()))
            && (this.getClients() == null ? other.getClients() == null : this.getClients().equals(other.getClients()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getPriority() == null) ? 0 : getPriority().hashCode());
        result = prime * result + ((getProxy() == null) ? 0 : getProxy().hashCode());
        result = prime * result + ((getClients() == null) ? 0 : getClients().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", nickname=").append(nickname);
        sb.append(", priority=").append(priority);
        sb.append(", proxy=").append(proxy);
        sb.append(", clients=").append(clients);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}