package com.media.video_meeting.entity;

import java.io.Serializable;

public class ClientMsg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.terminalname
     *
     * @mbggenerated
     */
    private String terminalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.serverip
     *
     * @mbggenerated
     */
    private String serverip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.volume
     *
     * @mbggenerated
     */
    private String volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.intercomenable
     *
     * @mbggenerated
     */
    private String intercomenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.cameraintercomenable
     *
     * @mbggenerated
     */
    private String cameraintercomenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.updatestatus
     *
     * @mbggenerated
     */
    private String updatestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.dhcpstatus
     *
     * @mbggenerated
     */
    private String dhcpstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.productsmodel
     *
     * @mbggenerated
     */
    private String productsmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_msg.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client_msg
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.userid
     *
     * @return the value of client_msg.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.userid
     *
     * @param userid the value for client_msg.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.id
     *
     * @return the value of client_msg.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.id
     *
     * @param id the value for client_msg.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.terminalname
     *
     * @return the value of client_msg.terminalname
     *
     * @mbggenerated
     */
    public String getTerminalname() {
        return terminalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.terminalname
     *
     * @param terminalname the value for client_msg.terminalname
     *
     * @mbggenerated
     */
    public void setTerminalname(String terminalname) {
        this.terminalname = terminalname == null ? null : terminalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.mac
     *
     * @return the value of client_msg.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.mac
     *
     * @param mac the value for client_msg.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.ip
     *
     * @return the value of client_msg.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.ip
     *
     * @param ip the value for client_msg.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.serverip
     *
     * @return the value of client_msg.serverip
     *
     * @mbggenerated
     */
    public String getServerip() {
        return serverip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.serverip
     *
     * @param serverip the value for client_msg.serverip
     *
     * @mbggenerated
     */
    public void setServerip(String serverip) {
        this.serverip = serverip == null ? null : serverip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.volume
     *
     * @return the value of client_msg.volume
     *
     * @mbggenerated
     */
    public String getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.volume
     *
     * @param volume the value for client_msg.volume
     *
     * @mbggenerated
     */
    public void setVolume(String volume) {
        this.volume = volume == null ? null : volume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.intercomenable
     *
     * @return the value of client_msg.intercomenable
     *
     * @mbggenerated
     */
    public String getIntercomenable() {
        return intercomenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.intercomenable
     *
     * @param intercomenable the value for client_msg.intercomenable
     *
     * @mbggenerated
     */
    public void setIntercomenable(String intercomenable) {
        this.intercomenable = intercomenable == null ? null : intercomenable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.cameraintercomenable
     *
     * @return the value of client_msg.cameraintercomenable
     *
     * @mbggenerated
     */
    public String getCameraintercomenable() {
        return cameraintercomenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.cameraintercomenable
     *
     * @param cameraintercomenable the value for client_msg.cameraintercomenable
     *
     * @mbggenerated
     */
    public void setCameraintercomenable(String cameraintercomenable) {
        this.cameraintercomenable = cameraintercomenable == null ? null : cameraintercomenable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.updatestatus
     *
     * @return the value of client_msg.updatestatus
     *
     * @mbggenerated
     */
    public String getUpdatestatus() {
        return updatestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.updatestatus
     *
     * @param updatestatus the value for client_msg.updatestatus
     *
     * @mbggenerated
     */
    public void setUpdatestatus(String updatestatus) {
        this.updatestatus = updatestatus == null ? null : updatestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.dhcpstatus
     *
     * @return the value of client_msg.dhcpstatus
     *
     * @mbggenerated
     */
    public String getDhcpstatus() {
        return dhcpstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.dhcpstatus
     *
     * @param dhcpstatus the value for client_msg.dhcpstatus
     *
     * @mbggenerated
     */
    public void setDhcpstatus(String dhcpstatus) {
        this.dhcpstatus = dhcpstatus == null ? null : dhcpstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.productsmodel
     *
     * @return the value of client_msg.productsmodel
     *
     * @mbggenerated
     */
    public String getProductsmodel() {
        return productsmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.productsmodel
     *
     * @param productsmodel the value for client_msg.productsmodel
     *
     * @mbggenerated
     */
    public void setProductsmodel(String productsmodel) {
        this.productsmodel = productsmodel == null ? null : productsmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_msg.status
     *
     * @return the value of client_msg.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_msg.status
     *
     * @param status the value for client_msg.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_msg
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClientMsg other = (ClientMsg) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTerminalname() == null ? other.getTerminalname() == null : this.getTerminalname().equals(other.getTerminalname()))
            && (this.getMac() == null ? other.getMac() == null : this.getMac().equals(other.getMac()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getServerip() == null ? other.getServerip() == null : this.getServerip().equals(other.getServerip()))
            && (this.getVolume() == null ? other.getVolume() == null : this.getVolume().equals(other.getVolume()))
            && (this.getIntercomenable() == null ? other.getIntercomenable() == null : this.getIntercomenable().equals(other.getIntercomenable()))
            && (this.getCameraintercomenable() == null ? other.getCameraintercomenable() == null : this.getCameraintercomenable().equals(other.getCameraintercomenable()))
            && (this.getUpdatestatus() == null ? other.getUpdatestatus() == null : this.getUpdatestatus().equals(other.getUpdatestatus()))
            && (this.getDhcpstatus() == null ? other.getDhcpstatus() == null : this.getDhcpstatus().equals(other.getDhcpstatus()))
            && (this.getProductsmodel() == null ? other.getProductsmodel() == null : this.getProductsmodel().equals(other.getProductsmodel()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_msg
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTerminalname() == null) ? 0 : getTerminalname().hashCode());
        result = prime * result + ((getMac() == null) ? 0 : getMac().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getServerip() == null) ? 0 : getServerip().hashCode());
        result = prime * result + ((getVolume() == null) ? 0 : getVolume().hashCode());
        result = prime * result + ((getIntercomenable() == null) ? 0 : getIntercomenable().hashCode());
        result = prime * result + ((getCameraintercomenable() == null) ? 0 : getCameraintercomenable().hashCode());
        result = prime * result + ((getUpdatestatus() == null) ? 0 : getUpdatestatus().hashCode());
        result = prime * result + ((getDhcpstatus() == null) ? 0 : getDhcpstatus().hashCode());
        result = prime * result + ((getProductsmodel() == null) ? 0 : getProductsmodel().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_msg
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", id=").append(id);
        sb.append(", terminalname=").append(terminalname);
        sb.append(", mac=").append(mac);
        sb.append(", ip=").append(ip);
        sb.append(", serverip=").append(serverip);
        sb.append(", volume=").append(volume);
        sb.append(", intercomenable=").append(intercomenable);
        sb.append(", cameraintercomenable=").append(cameraintercomenable);
        sb.append(", updatestatus=").append(updatestatus);
        sb.append(", dhcpstatus=").append(dhcpstatus);
        sb.append(", productsmodel=").append(productsmodel);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}