package com.media.video_meeting.entity;

import com.baomidou.mybatisplus.annotation.TableName;

import java.io.Serializable;

@TableName("meeting_moreinfo")
public class MeetingMoreInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.mid
     *
     * @mbggenerated
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.mpic
     *
     * @mbggenerated
     */
    private Integer mpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.webpic
     *
     * @mbggenerated
     */
    private Integer webpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.mpicmode
     *
     * @mbggenerated
     */
    private Integer mpicmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.grouptype
     *
     * @mbggenerated
     */
    private Integer grouptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.gourpip
     *
     * @mbggenerated
     */
    private String gourpip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.groupportyp
     *
     * @mbggenerated
     */
    private Integer groupportyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.groupportzsp
     *
     * @mbggenerated
     */
    private Integer groupportzsp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.groupportfsp
     *
     * @mbggenerated
     */
    private Integer groupportfsp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.spnl
     *
     * @mbggenerated
     */
    private Integer spnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.ypnl
     *
     * @mbggenerated
     */
    private Integer ypnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.hycc
     *
     * @mbggenerated
     */
    private Integer hycc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.zdhjzd
     *
     * @mbggenerated
     */
    private Integer zdhjzd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.zdsdcjhy
     *
     * @mbggenerated
     */
    private Integer zdsdcjhy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.fspml
     *
     * @mbggenerated
     */
    private Integer fspml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.fsplx
     *
     * @mbggenerated
     */
    private Integer fsplx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.fspnl
     *
     * @mbggenerated
     */
    private Integer fspnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.gbyzk
     *
     * @mbggenerated
     */
    private Integer gbyzk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.isopenipzdjs
     *
     * @mbggenerated
     */
    private Integer isopenipzdjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.ypjmsf
     *
     * @mbggenerated
     */
    private Integer ypjmsf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.zspjmsf
     *
     * @mbggenerated
     */
    private Integer zspjmsf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_moreinfo.fspjmsf
     *
     * @mbggenerated
     */
    private Integer fspjmsf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.id
     *
     * @return the value of meeting_moreinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.id
     *
     * @param id the value for meeting_moreinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.mid
     *
     * @return the value of meeting_moreinfo.mid
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.mid
     *
     * @param mid the value for meeting_moreinfo.mid
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.mpic
     *
     * @return the value of meeting_moreinfo.mpic
     *
     * @mbggenerated
     */
    public Integer getMpic() {
        return mpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.mpic
     *
     * @param mpic the value for meeting_moreinfo.mpic
     *
     * @mbggenerated
     */
    public void setMpic(Integer mpic) {
        this.mpic = mpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.webpic
     *
     * @return the value of meeting_moreinfo.webpic
     *
     * @mbggenerated
     */
    public Integer getWebpic() {
        return webpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.webpic
     *
     * @param webpic the value for meeting_moreinfo.webpic
     *
     * @mbggenerated
     */
    public void setWebpic(Integer webpic) {
        this.webpic = webpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.mpicmode
     *
     * @return the value of meeting_moreinfo.mpicmode
     *
     * @mbggenerated
     */
    public Integer getMpicmode() {
        return mpicmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.mpicmode
     *
     * @param mpicmode the value for meeting_moreinfo.mpicmode
     *
     * @mbggenerated
     */
    public void setMpicmode(Integer mpicmode) {
        this.mpicmode = mpicmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.grouptype
     *
     * @return the value of meeting_moreinfo.grouptype
     *
     * @mbggenerated
     */
    public Integer getGrouptype() {
        return grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.grouptype
     *
     * @param grouptype the value for meeting_moreinfo.grouptype
     *
     * @mbggenerated
     */
    public void setGrouptype(Integer grouptype) {
        this.grouptype = grouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.gourpip
     *
     * @return the value of meeting_moreinfo.gourpip
     *
     * @mbggenerated
     */
    public String getGourpip() {
        return gourpip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.gourpip
     *
     * @param gourpip the value for meeting_moreinfo.gourpip
     *
     * @mbggenerated
     */
    public void setGourpip(String gourpip) {
        this.gourpip = gourpip == null ? null : gourpip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.groupportyp
     *
     * @return the value of meeting_moreinfo.groupportyp
     *
     * @mbggenerated
     */
    public Integer getGroupportyp() {
        return groupportyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.groupportyp
     *
     * @param groupportyp the value for meeting_moreinfo.groupportyp
     *
     * @mbggenerated
     */
    public void setGroupportyp(Integer groupportyp) {
        this.groupportyp = groupportyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.groupportzsp
     *
     * @return the value of meeting_moreinfo.groupportzsp
     *
     * @mbggenerated
     */
    public Integer getGroupportzsp() {
        return groupportzsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.groupportzsp
     *
     * @param groupportzsp the value for meeting_moreinfo.groupportzsp
     *
     * @mbggenerated
     */
    public void setGroupportzsp(Integer groupportzsp) {
        this.groupportzsp = groupportzsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.groupportfsp
     *
     * @return the value of meeting_moreinfo.groupportfsp
     *
     * @mbggenerated
     */
    public Integer getGroupportfsp() {
        return groupportfsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.groupportfsp
     *
     * @param groupportfsp the value for meeting_moreinfo.groupportfsp
     *
     * @mbggenerated
     */
    public void setGroupportfsp(Integer groupportfsp) {
        this.groupportfsp = groupportfsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.spnl
     *
     * @return the value of meeting_moreinfo.spnl
     *
     * @mbggenerated
     */
    public Integer getSpnl() {
        return spnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.spnl
     *
     * @param spnl the value for meeting_moreinfo.spnl
     *
     * @mbggenerated
     */
    public void setSpnl(Integer spnl) {
        this.spnl = spnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.ypnl
     *
     * @return the value of meeting_moreinfo.ypnl
     *
     * @mbggenerated
     */
    public Integer getYpnl() {
        return ypnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.ypnl
     *
     * @param ypnl the value for meeting_moreinfo.ypnl
     *
     * @mbggenerated
     */
    public void setYpnl(Integer ypnl) {
        this.ypnl = ypnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.hycc
     *
     * @return the value of meeting_moreinfo.hycc
     *
     * @mbggenerated
     */
    public Integer getHycc() {
        return hycc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.hycc
     *
     * @param hycc the value for meeting_moreinfo.hycc
     *
     * @mbggenerated
     */
    public void setHycc(Integer hycc) {
        this.hycc = hycc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.zdhjzd
     *
     * @return the value of meeting_moreinfo.zdhjzd
     *
     * @mbggenerated
     */
    public Integer getZdhjzd() {
        return zdhjzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.zdhjzd
     *
     * @param zdhjzd the value for meeting_moreinfo.zdhjzd
     *
     * @mbggenerated
     */
    public void setZdhjzd(Integer zdhjzd) {
        this.zdhjzd = zdhjzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.zdsdcjhy
     *
     * @return the value of meeting_moreinfo.zdsdcjhy
     *
     * @mbggenerated
     */
    public Integer getZdsdcjhy() {
        return zdsdcjhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.zdsdcjhy
     *
     * @param zdsdcjhy the value for meeting_moreinfo.zdsdcjhy
     *
     * @mbggenerated
     */
    public void setZdsdcjhy(Integer zdsdcjhy) {
        this.zdsdcjhy = zdsdcjhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.fspml
     *
     * @return the value of meeting_moreinfo.fspml
     *
     * @mbggenerated
     */
    public Integer getFspml() {
        return fspml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.fspml
     *
     * @param fspml the value for meeting_moreinfo.fspml
     *
     * @mbggenerated
     */
    public void setFspml(Integer fspml) {
        this.fspml = fspml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.fsplx
     *
     * @return the value of meeting_moreinfo.fsplx
     *
     * @mbggenerated
     */
    public Integer getFsplx() {
        return fsplx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.fsplx
     *
     * @param fsplx the value for meeting_moreinfo.fsplx
     *
     * @mbggenerated
     */
    public void setFsplx(Integer fsplx) {
        this.fsplx = fsplx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.fspnl
     *
     * @return the value of meeting_moreinfo.fspnl
     *
     * @mbggenerated
     */
    public Integer getFspnl() {
        return fspnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.fspnl
     *
     * @param fspnl the value for meeting_moreinfo.fspnl
     *
     * @mbggenerated
     */
    public void setFspnl(Integer fspnl) {
        this.fspnl = fspnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.gbyzk
     *
     * @return the value of meeting_moreinfo.gbyzk
     *
     * @mbggenerated
     */
    public Integer getGbyzk() {
        return gbyzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.gbyzk
     *
     * @param gbyzk the value for meeting_moreinfo.gbyzk
     *
     * @mbggenerated
     */
    public void setGbyzk(Integer gbyzk) {
        this.gbyzk = gbyzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.isopenipzdjs
     *
     * @return the value of meeting_moreinfo.isopenipzdjs
     *
     * @mbggenerated
     */
    public Integer getIsopenipzdjs() {
        return isopenipzdjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.isopenipzdjs
     *
     * @param isopenipzdjs the value for meeting_moreinfo.isopenipzdjs
     *
     * @mbggenerated
     */
    public void setIsopenipzdjs(Integer isopenipzdjs) {
        this.isopenipzdjs = isopenipzdjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.ypjmsf
     *
     * @return the value of meeting_moreinfo.ypjmsf
     *
     * @mbggenerated
     */
    public Integer getYpjmsf() {
        return ypjmsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.ypjmsf
     *
     * @param ypjmsf the value for meeting_moreinfo.ypjmsf
     *
     * @mbggenerated
     */
    public void setYpjmsf(Integer ypjmsf) {
        this.ypjmsf = ypjmsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.zspjmsf
     *
     * @return the value of meeting_moreinfo.zspjmsf
     *
     * @mbggenerated
     */
    public Integer getZspjmsf() {
        return zspjmsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.zspjmsf
     *
     * @param zspjmsf the value for meeting_moreinfo.zspjmsf
     *
     * @mbggenerated
     */
    public void setZspjmsf(Integer zspjmsf) {
        this.zspjmsf = zspjmsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_moreinfo.fspjmsf
     *
     * @return the value of meeting_moreinfo.fspjmsf
     *
     * @mbggenerated
     */
    public Integer getFspjmsf() {
        return fspjmsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_moreinfo.fspjmsf
     *
     * @param fspjmsf the value for meeting_moreinfo.fspjmsf
     *
     * @mbggenerated
     */
    public void setFspjmsf(Integer fspjmsf) {
        this.fspjmsf = fspjmsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MeetingMoreInfo other = (MeetingMoreInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMid() == null ? other.getMid() == null : this.getMid().equals(other.getMid()))
            && (this.getMpic() == null ? other.getMpic() == null : this.getMpic().equals(other.getMpic()))
            && (this.getWebpic() == null ? other.getWebpic() == null : this.getWebpic().equals(other.getWebpic()))
            && (this.getMpicmode() == null ? other.getMpicmode() == null : this.getMpicmode().equals(other.getMpicmode()))
            && (this.getGrouptype() == null ? other.getGrouptype() == null : this.getGrouptype().equals(other.getGrouptype()))
            && (this.getGourpip() == null ? other.getGourpip() == null : this.getGourpip().equals(other.getGourpip()))
            && (this.getGroupportyp() == null ? other.getGroupportyp() == null : this.getGroupportyp().equals(other.getGroupportyp()))
            && (this.getGroupportzsp() == null ? other.getGroupportzsp() == null : this.getGroupportzsp().equals(other.getGroupportzsp()))
            && (this.getGroupportfsp() == null ? other.getGroupportfsp() == null : this.getGroupportfsp().equals(other.getGroupportfsp()))
            && (this.getSpnl() == null ? other.getSpnl() == null : this.getSpnl().equals(other.getSpnl()))
            && (this.getYpnl() == null ? other.getYpnl() == null : this.getYpnl().equals(other.getYpnl()))
            && (this.getHycc() == null ? other.getHycc() == null : this.getHycc().equals(other.getHycc()))
            && (this.getZdhjzd() == null ? other.getZdhjzd() == null : this.getZdhjzd().equals(other.getZdhjzd()))
            && (this.getZdsdcjhy() == null ? other.getZdsdcjhy() == null : this.getZdsdcjhy().equals(other.getZdsdcjhy()))
            && (this.getFspml() == null ? other.getFspml() == null : this.getFspml().equals(other.getFspml()))
            && (this.getFsplx() == null ? other.getFsplx() == null : this.getFsplx().equals(other.getFsplx()))
            && (this.getFspnl() == null ? other.getFspnl() == null : this.getFspnl().equals(other.getFspnl()))
            && (this.getGbyzk() == null ? other.getGbyzk() == null : this.getGbyzk().equals(other.getGbyzk()))
            && (this.getIsopenipzdjs() == null ? other.getIsopenipzdjs() == null : this.getIsopenipzdjs().equals(other.getIsopenipzdjs()))
            && (this.getYpjmsf() == null ? other.getYpjmsf() == null : this.getYpjmsf().equals(other.getYpjmsf()))
            && (this.getZspjmsf() == null ? other.getZspjmsf() == null : this.getZspjmsf().equals(other.getZspjmsf()))
            && (this.getFspjmsf() == null ? other.getFspjmsf() == null : this.getFspjmsf().equals(other.getFspjmsf()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMid() == null) ? 0 : getMid().hashCode());
        result = prime * result + ((getMpic() == null) ? 0 : getMpic().hashCode());
        result = prime * result + ((getWebpic() == null) ? 0 : getWebpic().hashCode());
        result = prime * result + ((getMpicmode() == null) ? 0 : getMpicmode().hashCode());
        result = prime * result + ((getGrouptype() == null) ? 0 : getGrouptype().hashCode());
        result = prime * result + ((getGourpip() == null) ? 0 : getGourpip().hashCode());
        result = prime * result + ((getGroupportyp() == null) ? 0 : getGroupportyp().hashCode());
        result = prime * result + ((getGroupportzsp() == null) ? 0 : getGroupportzsp().hashCode());
        result = prime * result + ((getGroupportfsp() == null) ? 0 : getGroupportfsp().hashCode());
        result = prime * result + ((getSpnl() == null) ? 0 : getSpnl().hashCode());
        result = prime * result + ((getYpnl() == null) ? 0 : getYpnl().hashCode());
        result = prime * result + ((getHycc() == null) ? 0 : getHycc().hashCode());
        result = prime * result + ((getZdhjzd() == null) ? 0 : getZdhjzd().hashCode());
        result = prime * result + ((getZdsdcjhy() == null) ? 0 : getZdsdcjhy().hashCode());
        result = prime * result + ((getFspml() == null) ? 0 : getFspml().hashCode());
        result = prime * result + ((getFsplx() == null) ? 0 : getFsplx().hashCode());
        result = prime * result + ((getFspnl() == null) ? 0 : getFspnl().hashCode());
        result = prime * result + ((getGbyzk() == null) ? 0 : getGbyzk().hashCode());
        result = prime * result + ((getIsopenipzdjs() == null) ? 0 : getIsopenipzdjs().hashCode());
        result = prime * result + ((getYpjmsf() == null) ? 0 : getYpjmsf().hashCode());
        result = prime * result + ((getZspjmsf() == null) ? 0 : getZspjmsf().hashCode());
        result = prime * result + ((getFspjmsf() == null) ? 0 : getFspjmsf().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mid=").append(mid);
        sb.append(", mpic=").append(mpic);
        sb.append(", webpic=").append(webpic);
        sb.append(", mpicmode=").append(mpicmode);
        sb.append(", grouptype=").append(grouptype);
        sb.append(", gourpip=").append(gourpip);
        sb.append(", groupportyp=").append(groupportyp);
        sb.append(", groupportzsp=").append(groupportzsp);
        sb.append(", groupportfsp=").append(groupportfsp);
        sb.append(", spnl=").append(spnl);
        sb.append(", ypnl=").append(ypnl);
        sb.append(", hycc=").append(hycc);
        sb.append(", zdhjzd=").append(zdhjzd);
        sb.append(", zdsdcjhy=").append(zdsdcjhy);
        sb.append(", fspml=").append(fspml);
        sb.append(", fsplx=").append(fsplx);
        sb.append(", fspnl=").append(fspnl);
        sb.append(", gbyzk=").append(gbyzk);
        sb.append(", isopenipzdjs=").append(isopenipzdjs);
        sb.append(", ypjmsf=").append(ypjmsf);
        sb.append(", zspjmsf=").append(zspjmsf);
        sb.append(", fspjmsf=").append(fspjmsf);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}