package com.media.video_meeting.entity;

import com.baomidou.mybatisplus.annotation.TableName;

import java.io.Serializable;
import java.util.Date;

@TableName("meeting")
public class Meeting implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.time
     *
     * @mbggenerated
     */
    private Integer time;
    private String timeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.isfoerver
     *
     * @mbggenerated
     */
    private Integer isfoerver = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.ml
     *
     * @mbggenerated
     */
    private Integer ml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.fs
     *
     * @mbggenerated
     */
    private Integer fs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.lk
     *
     * @mbggenerated
     */
    private Integer lk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.info
     *
     * @mbggenerated
     */
    private String info;

    private Integer[] client_ids;//终端列表
    private Integer client_start;//发起者终端编号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.hystate
     *
     * @mbggenerated
     */
    private Integer hystate = 1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.createtime
     *
     * @mbggenerated
     */
    private Long createtime = new Date().getTime();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.id
     *
     * @return the value of meeting.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.id
     *
     * @param id the value for meeting.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.name
     *
     * @return the value of meeting.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.name
     *
     * @param name the value for meeting.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.number
     *
     * @return the value of meeting.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.number
     *
     * @param number the value for meeting.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.time
     *
     * @return the value of meeting.time
     *
     * @mbggenerated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.time
     *
     * @param time the value for meeting.time
     *
     * @mbggenerated
     */
    public void setTime(Integer time) {
        this.time = time;
        StringBuilder sb = new StringBuilder();
        int h = time/1000/60/60;
        int m = time/1000/60%60;
        this.setTimeStr(sb.append(h).append("时").append(m).append("分").toString());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.isfoerver
     *
     * @return the value of meeting.isfoerver
     *
     * @mbggenerated
     */
    public Integer getIsfoerver() {
        return isfoerver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.isfoerver
     *
     * @param isfoerver the value for meeting.isfoerver
     *
     * @mbggenerated
     */
    public void setIsfoerver(Integer isfoerver) {
        this.isfoerver = isfoerver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.ml
     *
     * @return the value of meeting.ml
     *
     * @mbggenerated
     */
    public Integer getMl() {
        return ml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.ml
     *
     * @param ml the value for meeting.ml
     *
     * @mbggenerated
     */
    public void setMl(Integer ml) {
        this.ml = ml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.password
     *
     * @return the value of meeting.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.password
     *
     * @param password the value for meeting.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.type
     *
     * @return the value of meeting.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.type
     *
     * @param type the value for meeting.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.fs
     *
     * @return the value of meeting.fs
     *
     * @mbggenerated
     */
    public Integer getFs() {
        return fs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.fs
     *
     * @param fs the value for meeting.fs
     *
     * @mbggenerated
     */
    public void setFs(Integer fs) {
        this.fs = fs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.lk
     *
     * @return the value of meeting.lk
     *
     * @mbggenerated
     */
    public Integer getLk() {
        return lk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.lk
     *
     * @param lk the value for meeting.lk
     *
     * @mbggenerated
     */
    public void setLk(Integer lk) {
        this.lk = lk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.info
     *
     * @return the value of meeting.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.info
     *
     * @param info the value for meeting.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.hystate
     *
     * @return the value of meeting.hystate
     *
     * @mbggenerated
     */
    public Integer getHystate() {
        return hystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.hystate
     *
     * @param hystate the value for meeting.hystate
     *
     * @mbggenerated
     */
    public void setHystate(Integer hystate) {
        this.hystate = hystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.createtime
     *
     * @return the value of meeting.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.createtime
     *
     * @param createtime the value for meeting.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    public String getTimeStr() {
        return timeStr;
    }

    public void setTimeStr(String timeStr) {
        this.timeStr = timeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Meeting other = (Meeting) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getIsfoerver() == null ? other.getIsfoerver() == null : this.getIsfoerver().equals(other.getIsfoerver()))
            && (this.getMl() == null ? other.getMl() == null : this.getMl().equals(other.getMl()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getFs() == null ? other.getFs() == null : this.getFs().equals(other.getFs()))
            && (this.getLk() == null ? other.getLk() == null : this.getLk().equals(other.getLk()))
            && (this.getInfo() == null ? other.getInfo() == null : this.getInfo().equals(other.getInfo()))
            && (this.getHystate() == null ? other.getHystate() == null : this.getHystate().equals(other.getHystate()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getIsfoerver() == null) ? 0 : getIsfoerver().hashCode());
        result = prime * result + ((getMl() == null) ? 0 : getMl().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getFs() == null) ? 0 : getFs().hashCode());
        result = prime * result + ((getLk() == null) ? 0 : getLk().hashCode());
        result = prime * result + ((getInfo() == null) ? 0 : getInfo().hashCode());
        result = prime * result + ((getHystate() == null) ? 0 : getHystate().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", number=").append(number);
        sb.append(", time=").append(time);
        sb.append(", isfoerver=").append(isfoerver);
        sb.append(", ml=").append(ml);
        sb.append(", password=").append(password);
        sb.append(", type=").append(type);
        sb.append(", fs=").append(fs);
        sb.append(", lk=").append(lk);
        sb.append(", info=").append(info);
        sb.append(", hystate=").append(hystate);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public Integer[] getClient_ids() {
        return client_ids;
    }

    public void setClient_ids(Integer[] client_ids) {
        this.client_ids = client_ids;
    }

    public Integer getClient_start() {
        return client_start;
    }

    public void setClient_start(Integer client_start) {
        this.client_start = client_start;
    }
}