package com.media.video_meeting.entity;

import java.io.Serializable;

public class ModelS implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_s.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_s.mid
     *
     * @mbggenerated
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_s.mnumber
     *
     * @mbggenerated
     */
    private Integer mnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_s.mstate
     *
     * @mbggenerated
     */
    private Integer mstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_s.mversion
     *
     * @mbggenerated
     */
    private String mversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table model_s
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_s.id
     *
     * @return the value of model_s.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_s.id
     *
     * @param id the value for model_s.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_s.mid
     *
     * @return the value of model_s.mid
     *
     * @mbggenerated
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_s.mid
     *
     * @param mid the value for model_s.mid
     *
     * @mbggenerated
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_s.mnumber
     *
     * @return the value of model_s.mnumber
     *
     * @mbggenerated
     */
    public Integer getMnumber() {
        return mnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_s.mnumber
     *
     * @param mnumber the value for model_s.mnumber
     *
     * @mbggenerated
     */
    public void setMnumber(Integer mnumber) {
        this.mnumber = mnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_s.mstate
     *
     * @return the value of model_s.mstate
     *
     * @mbggenerated
     */
    public Integer getMstate() {
        return mstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_s.mstate
     *
     * @param mstate the value for model_s.mstate
     *
     * @mbggenerated
     */
    public void setMstate(Integer mstate) {
        this.mstate = mstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_s.mversion
     *
     * @return the value of model_s.mversion
     *
     * @mbggenerated
     */
    public String getMversion() {
        return mversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_s.mversion
     *
     * @param mversion the value for model_s.mversion
     *
     * @mbggenerated
     */
    public void setMversion(String mversion) {
        this.mversion = mversion == null ? null : mversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ModelS other = (ModelS) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMid() == null ? other.getMid() == null : this.getMid().equals(other.getMid()))
            && (this.getMnumber() == null ? other.getMnumber() == null : this.getMnumber().equals(other.getMnumber()))
            && (this.getMstate() == null ? other.getMstate() == null : this.getMstate().equals(other.getMstate()))
            && (this.getMversion() == null ? other.getMversion() == null : this.getMversion().equals(other.getMversion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMid() == null) ? 0 : getMid().hashCode());
        result = prime * result + ((getMnumber() == null) ? 0 : getMnumber().hashCode());
        result = prime * result + ((getMstate() == null) ? 0 : getMstate().hashCode());
        result = prime * result + ((getMversion() == null) ? 0 : getMversion().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mid=").append(mid);
        sb.append(", mnumber=").append(mnumber);
        sb.append(", mstate=").append(mstate);
        sb.append(", mversion=").append(mversion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}