package com.media.video_meeting.entity;

import java.io.Serializable;

public class Task implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.taskid
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.solution
     *
     * @mbggenerated
     */
    private String solution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.branch
     *
     * @mbggenerated
     */
    private String branch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.taskPriority
     *
     * @mbggenerated
     */
    private Integer taskpriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.taskname
     *
     * @mbggenerated
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.taskclassify
     *
     * @mbggenerated
     */
    private Integer taskclassify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.playOrder
     *
     * @mbggenerated
     */
    private Integer playorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.startDate
     *
     * @mbggenerated
     */
    private String startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.startTime
     *
     * @mbggenerated
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.stopDate
     *
     * @mbggenerated
     */
    private String stopdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.isenddate
     *
     * @mbggenerated
     */
    private Integer isenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.duration
     *
     * @mbggenerated
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.isduration
     *
     * @mbggenerated
     */
    private Integer isduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.startinadvance
     *
     * @mbggenerated
     */
    private Integer startinadvance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.mp3
     *
     * @mbggenerated
     */
    private String mp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.loopType
     *
     * @mbggenerated
     */
    private Integer looptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.muiscduration
     *
     * @mbggenerated
     */
    private Integer muiscduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.samll
     *
     * @mbggenerated
     */
    private Integer samll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.volume
     *
     * @mbggenerated
     */
    private Integer volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.keybind
     *
     * @mbggenerated
     */
    private Integer keybind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.weekMask
     *
     * @mbggenerated
     */
    private Integer weekmask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.users
     *
     * @mbggenerated
     */
    private String users;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.collectionclient
     *
     * @mbggenerated
     */
    private String collectionclient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.fireTerminal
     *
     * @mbggenerated
     */
    private Integer fireterminal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.port
     *
     * @mbggenerated
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.isLevel
     *
     * @mbggenerated
     */
    private Integer islevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.isExternalMusic
     *
     * @mbggenerated
     */
    private Integer isexternalmusic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.externalFireTerminal
     *
     * @mbggenerated
     */
    private String externalfireterminal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.reporter
     *
     * @mbggenerated
     */
    private Integer reporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.speed
     *
     * @mbggenerated
     */
    private Integer speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.loopNum
     *
     * @mbggenerated
     */
    private Integer loopnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.taskType
     *
     * @mbggenerated
     */
    private Integer tasktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.taskid
     *
     * @return the value of task.taskid
     *
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.taskid
     *
     * @param taskid the value for task.taskid
     *
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.solution
     *
     * @return the value of task.solution
     *
     * @mbggenerated
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.solution
     *
     * @param solution the value for task.solution
     *
     * @mbggenerated
     */
    public void setSolution(String solution) {
        this.solution = solution == null ? null : solution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.branch
     *
     * @return the value of task.branch
     *
     * @mbggenerated
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.branch
     *
     * @param branch the value for task.branch
     *
     * @mbggenerated
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.taskPriority
     *
     * @return the value of task.taskPriority
     *
     * @mbggenerated
     */
    public Integer getTaskpriority() {
        return taskpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.taskPriority
     *
     * @param taskpriority the value for task.taskPriority
     *
     * @mbggenerated
     */
    public void setTaskpriority(Integer taskpriority) {
        this.taskpriority = taskpriority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.taskname
     *
     * @return the value of task.taskname
     *
     * @mbggenerated
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.taskname
     *
     * @param taskname the value for task.taskname
     *
     * @mbggenerated
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname == null ? null : taskname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.taskclassify
     *
     * @return the value of task.taskclassify
     *
     * @mbggenerated
     */
    public Integer getTaskclassify() {
        return taskclassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.taskclassify
     *
     * @param taskclassify the value for task.taskclassify
     *
     * @mbggenerated
     */
    public void setTaskclassify(Integer taskclassify) {
        this.taskclassify = taskclassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.playOrder
     *
     * @return the value of task.playOrder
     *
     * @mbggenerated
     */
    public Integer getPlayorder() {
        return playorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.playOrder
     *
     * @param playorder the value for task.playOrder
     *
     * @mbggenerated
     */
    public void setPlayorder(Integer playorder) {
        this.playorder = playorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.startDate
     *
     * @return the value of task.startDate
     *
     * @mbggenerated
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.startDate
     *
     * @param startdate the value for task.startDate
     *
     * @mbggenerated
     */
    public void setStartdate(String startdate) {
        this.startdate = startdate == null ? null : startdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.startTime
     *
     * @return the value of task.startTime
     *
     * @mbggenerated
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.startTime
     *
     * @param starttime the value for task.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.stopDate
     *
     * @return the value of task.stopDate
     *
     * @mbggenerated
     */
    public String getStopdate() {
        return stopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.stopDate
     *
     * @param stopdate the value for task.stopDate
     *
     * @mbggenerated
     */
    public void setStopdate(String stopdate) {
        this.stopdate = stopdate == null ? null : stopdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.isenddate
     *
     * @return the value of task.isenddate
     *
     * @mbggenerated
     */
    public Integer getIsenddate() {
        return isenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.isenddate
     *
     * @param isenddate the value for task.isenddate
     *
     * @mbggenerated
     */
    public void setIsenddate(Integer isenddate) {
        this.isenddate = isenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.duration
     *
     * @return the value of task.duration
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.duration
     *
     * @param duration the value for task.duration
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.isduration
     *
     * @return the value of task.isduration
     *
     * @mbggenerated
     */
    public Integer getIsduration() {
        return isduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.isduration
     *
     * @param isduration the value for task.isduration
     *
     * @mbggenerated
     */
    public void setIsduration(Integer isduration) {
        this.isduration = isduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.startinadvance
     *
     * @return the value of task.startinadvance
     *
     * @mbggenerated
     */
    public Integer getStartinadvance() {
        return startinadvance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.startinadvance
     *
     * @param startinadvance the value for task.startinadvance
     *
     * @mbggenerated
     */
    public void setStartinadvance(Integer startinadvance) {
        this.startinadvance = startinadvance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.mp3
     *
     * @return the value of task.mp3
     *
     * @mbggenerated
     */
    public String getMp3() {
        return mp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.mp3
     *
     * @param mp3 the value for task.mp3
     *
     * @mbggenerated
     */
    public void setMp3(String mp3) {
        this.mp3 = mp3 == null ? null : mp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.loopType
     *
     * @return the value of task.loopType
     *
     * @mbggenerated
     */
    public Integer getLooptype() {
        return looptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.loopType
     *
     * @param looptype the value for task.loopType
     *
     * @mbggenerated
     */
    public void setLooptype(Integer looptype) {
        this.looptype = looptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.muiscduration
     *
     * @return the value of task.muiscduration
     *
     * @mbggenerated
     */
    public Integer getMuiscduration() {
        return muiscduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.muiscduration
     *
     * @param muiscduration the value for task.muiscduration
     *
     * @mbggenerated
     */
    public void setMuiscduration(Integer muiscduration) {
        this.muiscduration = muiscduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.samll
     *
     * @return the value of task.samll
     *
     * @mbggenerated
     */
    public Integer getSamll() {
        return samll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.samll
     *
     * @param samll the value for task.samll
     *
     * @mbggenerated
     */
    public void setSamll(Integer samll) {
        this.samll = samll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.volume
     *
     * @return the value of task.volume
     *
     * @mbggenerated
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.volume
     *
     * @param volume the value for task.volume
     *
     * @mbggenerated
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.keybind
     *
     * @return the value of task.keybind
     *
     * @mbggenerated
     */
    public Integer getKeybind() {
        return keybind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.keybind
     *
     * @param keybind the value for task.keybind
     *
     * @mbggenerated
     */
    public void setKeybind(Integer keybind) {
        this.keybind = keybind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.weekMask
     *
     * @return the value of task.weekMask
     *
     * @mbggenerated
     */
    public Integer getWeekmask() {
        return weekmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.weekMask
     *
     * @param weekmask the value for task.weekMask
     *
     * @mbggenerated
     */
    public void setWeekmask(Integer weekmask) {
        this.weekmask = weekmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.users
     *
     * @return the value of task.users
     *
     * @mbggenerated
     */
    public String getUsers() {
        return users;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.users
     *
     * @param users the value for task.users
     *
     * @mbggenerated
     */
    public void setUsers(String users) {
        this.users = users == null ? null : users.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.collectionclient
     *
     * @return the value of task.collectionclient
     *
     * @mbggenerated
     */
    public String getCollectionclient() {
        return collectionclient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.collectionclient
     *
     * @param collectionclient the value for task.collectionclient
     *
     * @mbggenerated
     */
    public void setCollectionclient(String collectionclient) {
        this.collectionclient = collectionclient == null ? null : collectionclient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.area
     *
     * @return the value of task.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.area
     *
     * @param area the value for task.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.fireTerminal
     *
     * @return the value of task.fireTerminal
     *
     * @mbggenerated
     */
    public Integer getFireterminal() {
        return fireterminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.fireTerminal
     *
     * @param fireterminal the value for task.fireTerminal
     *
     * @mbggenerated
     */
    public void setFireterminal(Integer fireterminal) {
        this.fireterminal = fireterminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.port
     *
     * @return the value of task.port
     *
     * @mbggenerated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.port
     *
     * @param port the value for task.port
     *
     * @mbggenerated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.isLevel
     *
     * @return the value of task.isLevel
     *
     * @mbggenerated
     */
    public Integer getIslevel() {
        return islevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.isLevel
     *
     * @param islevel the value for task.isLevel
     *
     * @mbggenerated
     */
    public void setIslevel(Integer islevel) {
        this.islevel = islevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.isExternalMusic
     *
     * @return the value of task.isExternalMusic
     *
     * @mbggenerated
     */
    public Integer getIsexternalmusic() {
        return isexternalmusic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.isExternalMusic
     *
     * @param isexternalmusic the value for task.isExternalMusic
     *
     * @mbggenerated
     */
    public void setIsexternalmusic(Integer isexternalmusic) {
        this.isexternalmusic = isexternalmusic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.externalFireTerminal
     *
     * @return the value of task.externalFireTerminal
     *
     * @mbggenerated
     */
    public String getExternalfireterminal() {
        return externalfireterminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.externalFireTerminal
     *
     * @param externalfireterminal the value for task.externalFireTerminal
     *
     * @mbggenerated
     */
    public void setExternalfireterminal(String externalfireterminal) {
        this.externalfireterminal = externalfireterminal == null ? null : externalfireterminal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.info
     *
     * @return the value of task.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.info
     *
     * @param info the value for task.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.reporter
     *
     * @return the value of task.reporter
     *
     * @mbggenerated
     */
    public Integer getReporter() {
        return reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.reporter
     *
     * @param reporter the value for task.reporter
     *
     * @mbggenerated
     */
    public void setReporter(Integer reporter) {
        this.reporter = reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.speed
     *
     * @return the value of task.speed
     *
     * @mbggenerated
     */
    public Integer getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.speed
     *
     * @param speed the value for task.speed
     *
     * @mbggenerated
     */
    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.loopNum
     *
     * @return the value of task.loopNum
     *
     * @mbggenerated
     */
    public Integer getLoopnum() {
        return loopnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.loopNum
     *
     * @param loopnum the value for task.loopNum
     *
     * @mbggenerated
     */
    public void setLoopnum(Integer loopnum) {
        this.loopnum = loopnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.taskType
     *
     * @return the value of task.taskType
     *
     * @mbggenerated
     */
    public Integer getTasktype() {
        return tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.taskType
     *
     * @param tasktype the value for task.taskType
     *
     * @mbggenerated
     */
    public void setTasktype(Integer tasktype) {
        this.tasktype = tasktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Task other = (Task) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTaskid() == null ? other.getTaskid() == null : this.getTaskid().equals(other.getTaskid()))
            && (this.getSolution() == null ? other.getSolution() == null : this.getSolution().equals(other.getSolution()))
            && (this.getBranch() == null ? other.getBranch() == null : this.getBranch().equals(other.getBranch()))
            && (this.getTaskpriority() == null ? other.getTaskpriority() == null : this.getTaskpriority().equals(other.getTaskpriority()))
            && (this.getTaskname() == null ? other.getTaskname() == null : this.getTaskname().equals(other.getTaskname()))
            && (this.getTaskclassify() == null ? other.getTaskclassify() == null : this.getTaskclassify().equals(other.getTaskclassify()))
            && (this.getPlayorder() == null ? other.getPlayorder() == null : this.getPlayorder().equals(other.getPlayorder()))
            && (this.getStartdate() == null ? other.getStartdate() == null : this.getStartdate().equals(other.getStartdate()))
            && (this.getStarttime() == null ? other.getStarttime() == null : this.getStarttime().equals(other.getStarttime()))
            && (this.getStopdate() == null ? other.getStopdate() == null : this.getStopdate().equals(other.getStopdate()))
            && (this.getIsenddate() == null ? other.getIsenddate() == null : this.getIsenddate().equals(other.getIsenddate()))
            && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
            && (this.getIsduration() == null ? other.getIsduration() == null : this.getIsduration().equals(other.getIsduration()))
            && (this.getStartinadvance() == null ? other.getStartinadvance() == null : this.getStartinadvance().equals(other.getStartinadvance()))
            && (this.getMp3() == null ? other.getMp3() == null : this.getMp3().equals(other.getMp3()))
            && (this.getLooptype() == null ? other.getLooptype() == null : this.getLooptype().equals(other.getLooptype()))
            && (this.getMuiscduration() == null ? other.getMuiscduration() == null : this.getMuiscduration().equals(other.getMuiscduration()))
            && (this.getSamll() == null ? other.getSamll() == null : this.getSamll().equals(other.getSamll()))
            && (this.getVolume() == null ? other.getVolume() == null : this.getVolume().equals(other.getVolume()))
            && (this.getKeybind() == null ? other.getKeybind() == null : this.getKeybind().equals(other.getKeybind()))
            && (this.getWeekmask() == null ? other.getWeekmask() == null : this.getWeekmask().equals(other.getWeekmask()))
            && (this.getUsers() == null ? other.getUsers() == null : this.getUsers().equals(other.getUsers()))
            && (this.getCollectionclient() == null ? other.getCollectionclient() == null : this.getCollectionclient().equals(other.getCollectionclient()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getFireterminal() == null ? other.getFireterminal() == null : this.getFireterminal().equals(other.getFireterminal()))
            && (this.getPort() == null ? other.getPort() == null : this.getPort().equals(other.getPort()))
            && (this.getIslevel() == null ? other.getIslevel() == null : this.getIslevel().equals(other.getIslevel()))
            && (this.getIsexternalmusic() == null ? other.getIsexternalmusic() == null : this.getIsexternalmusic().equals(other.getIsexternalmusic()))
            && (this.getExternalfireterminal() == null ? other.getExternalfireterminal() == null : this.getExternalfireterminal().equals(other.getExternalfireterminal()))
            && (this.getInfo() == null ? other.getInfo() == null : this.getInfo().equals(other.getInfo()))
            && (this.getReporter() == null ? other.getReporter() == null : this.getReporter().equals(other.getReporter()))
            && (this.getSpeed() == null ? other.getSpeed() == null : this.getSpeed().equals(other.getSpeed()))
            && (this.getLoopnum() == null ? other.getLoopnum() == null : this.getLoopnum().equals(other.getLoopnum()))
            && (this.getTasktype() == null ? other.getTasktype() == null : this.getTasktype().equals(other.getTasktype()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTaskid() == null) ? 0 : getTaskid().hashCode());
        result = prime * result + ((getSolution() == null) ? 0 : getSolution().hashCode());
        result = prime * result + ((getBranch() == null) ? 0 : getBranch().hashCode());
        result = prime * result + ((getTaskpriority() == null) ? 0 : getTaskpriority().hashCode());
        result = prime * result + ((getTaskname() == null) ? 0 : getTaskname().hashCode());
        result = prime * result + ((getTaskclassify() == null) ? 0 : getTaskclassify().hashCode());
        result = prime * result + ((getPlayorder() == null) ? 0 : getPlayorder().hashCode());
        result = prime * result + ((getStartdate() == null) ? 0 : getStartdate().hashCode());
        result = prime * result + ((getStarttime() == null) ? 0 : getStarttime().hashCode());
        result = prime * result + ((getStopdate() == null) ? 0 : getStopdate().hashCode());
        result = prime * result + ((getIsenddate() == null) ? 0 : getIsenddate().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getIsduration() == null) ? 0 : getIsduration().hashCode());
        result = prime * result + ((getStartinadvance() == null) ? 0 : getStartinadvance().hashCode());
        result = prime * result + ((getMp3() == null) ? 0 : getMp3().hashCode());
        result = prime * result + ((getLooptype() == null) ? 0 : getLooptype().hashCode());
        result = prime * result + ((getMuiscduration() == null) ? 0 : getMuiscduration().hashCode());
        result = prime * result + ((getSamll() == null) ? 0 : getSamll().hashCode());
        result = prime * result + ((getVolume() == null) ? 0 : getVolume().hashCode());
        result = prime * result + ((getKeybind() == null) ? 0 : getKeybind().hashCode());
        result = prime * result + ((getWeekmask() == null) ? 0 : getWeekmask().hashCode());
        result = prime * result + ((getUsers() == null) ? 0 : getUsers().hashCode());
        result = prime * result + ((getCollectionclient() == null) ? 0 : getCollectionclient().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getFireterminal() == null) ? 0 : getFireterminal().hashCode());
        result = prime * result + ((getPort() == null) ? 0 : getPort().hashCode());
        result = prime * result + ((getIslevel() == null) ? 0 : getIslevel().hashCode());
        result = prime * result + ((getIsexternalmusic() == null) ? 0 : getIsexternalmusic().hashCode());
        result = prime * result + ((getExternalfireterminal() == null) ? 0 : getExternalfireterminal().hashCode());
        result = prime * result + ((getInfo() == null) ? 0 : getInfo().hashCode());
        result = prime * result + ((getReporter() == null) ? 0 : getReporter().hashCode());
        result = prime * result + ((getSpeed() == null) ? 0 : getSpeed().hashCode());
        result = prime * result + ((getLoopnum() == null) ? 0 : getLoopnum().hashCode());
        result = prime * result + ((getTasktype() == null) ? 0 : getTasktype().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskid=").append(taskid);
        sb.append(", solution=").append(solution);
        sb.append(", branch=").append(branch);
        sb.append(", taskpriority=").append(taskpriority);
        sb.append(", taskname=").append(taskname);
        sb.append(", taskclassify=").append(taskclassify);
        sb.append(", playorder=").append(playorder);
        sb.append(", startdate=").append(startdate);
        sb.append(", starttime=").append(starttime);
        sb.append(", stopdate=").append(stopdate);
        sb.append(", isenddate=").append(isenddate);
        sb.append(", duration=").append(duration);
        sb.append(", isduration=").append(isduration);
        sb.append(", startinadvance=").append(startinadvance);
        sb.append(", mp3=").append(mp3);
        sb.append(", looptype=").append(looptype);
        sb.append(", muiscduration=").append(muiscduration);
        sb.append(", samll=").append(samll);
        sb.append(", volume=").append(volume);
        sb.append(", keybind=").append(keybind);
        sb.append(", weekmask=").append(weekmask);
        sb.append(", users=").append(users);
        sb.append(", collectionclient=").append(collectionclient);
        sb.append(", area=").append(area);
        sb.append(", fireterminal=").append(fireterminal);
        sb.append(", port=").append(port);
        sb.append(", islevel=").append(islevel);
        sb.append(", isexternalmusic=").append(isexternalmusic);
        sb.append(", externalfireterminal=").append(externalfireterminal);
        sb.append(", info=").append(info);
        sb.append(", reporter=").append(reporter);
        sb.append(", speed=").append(speed);
        sb.append(", loopnum=").append(loopnum);
        sb.append(", tasktype=").append(tasktype);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}