package com.media.video_meeting.dao;

import com.media.video_meeting.entity.Branch;

public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    int insertSelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    Branch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table branch
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Branch record);
}