package com.media.video_meeting.dao;

import com.media.video_meeting.entity.ClientGroup;

import java.util.List;

public interface ClientGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_group
     *
     * @mbggenerated
     */
    int insert(ClientGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_group
     *
     * @mbggenerated
     */
    int insertSelective(ClientGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_group
     *
     * @mbggenerated
     */
    ClientGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClientGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClientGroup record);

    List<ClientGroup> queryAllGroup();

    List<ClientGroup> queryAllGroupJoinClient();

    int deleteGroup(Integer id);
}