package com.media.video_meeting.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.media.video_meeting.entity.MeetingMoreInfo;

public interface MeetingMoreInfoMapper extends BaseMapper<MeetingMoreInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    int insert(MeetingMoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    int insertSelective(MeetingMoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    MeetingMoreInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MeetingMoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_moreinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MeetingMoreInfo record);

    MeetingMoreInfo selectDefaultMeetingMoreInfo();

    int deleteByMid(Integer mid);
}