package com.media.video_meeting.dao;

import com.media.video_meeting.entity.ModelS;

public interface ModelSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    int insert(ModelS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    int insertSelective(ModelS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    ModelS selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ModelS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_s
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ModelS record);
}