package com.media.video_meeting.dao;

import com.media.video_meeting.entity.Model;

import java.util.List;

public interface ModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated
     */
    int insert(Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated
     */
    int insertSelective(Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated
     */
    Model selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Model record);


    List<Model> queryAll();
}