package com.media.video_meeting.dao;

import com.media.video_meeting.entity.SystemLog;

import java.util.List;

public interface SystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated
     */
    int insert(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated
     */
    int insertSelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated
     */
    SystemLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemLog record);

    int clearLog();

    List<SystemLog> queryAll();
}